# Cấu hình ứng dụng trong môi trường phát triển
spring:
  profiles: prod
  # Cấu hình khác cho môi trường phát triển
  datasource:
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: myusername
    password: mypassword